import DashNav from "@/components/DashNav";

export const metadata = {
  title: "Dashboard - Invoice app",
  description: "Generated by create next app",
};

export default function DashLayout({ children }) {
  return (
    <>
      <DashNav />

      {children}
    </>
  );
}

export const dynamic = "force-dynamic";
